//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCompany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDailyReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDailyReport()
        {
            this.tblDailyReportByProjects = new HashSet<tblDailyReportByProject>();
        }
    
        public int DailyReportID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> HoursWorking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDailyReportByProject> tblDailyReportByProjects { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
