//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCompany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeEdit
    {
        public int EmployeeID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public Nullable<int> Salary { get; set; }
        public string QualificationsLevel { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblManager tblManager { get; set; }
        public virtual tblPosition tblPosition { get; set; }
        public virtual tblSector tblSector { get; set; }
    }
}
