//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCompany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProject()
        {
            this.tblDailyReportByProjects = new HashSet<tblDailyReportByProject>();
            this.tblAccounts = new HashSet<tblAccount>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public int ClientID { get; set; }
        public System.DateTime SigningDate { get; set; }
        public int ManagerSignedID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EstimatedEndDate { get; set; }
        public Nullable<int> HourlyWage { get; set; }
        public Nullable<int> Realization { get; set; }
        public int ManagerRunningID { get; set; }
        public string ClientProjectName { get; set; }
    
        public virtual tblClient tblClient { get; set; }
        public virtual tblManager tblManager { get; set; }
        public virtual tblManager tblManager1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDailyReportByProject> tblDailyReportByProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccount> tblAccounts { get; set; }
    }
}
