//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCompany.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwManager
    {
        public int ManagerID { get; set; }
        public int AccountID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JMBG { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<int> ResponsibilityLevel { get; set; }
        public Nullable<int> NumberOfRealizations { get; set; }
        public Nullable<int> Salaty { get; set; }
        public Nullable<int> OfficeNumber { get; set; }
    }
}
